//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pp_01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pp01Entities4 : DbContext
    {
        public pp01Entities4()
            : base("name=pp01Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gruppa> Gruppa { get; set; }
        public virtual DbSet<Obuchau> Obuchau { get; set; }
        public virtual DbSet<Raspicanie> Raspicanie { get; set; }
        public virtual DbSet<Trener> Trener { get; set; }
    }
}
