//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pp_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obuchau
    {
        public int id_obuch { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public Nullable<System.DateTime> data_rozd { get; set; }
        public Nullable<int> id_gruppa { get; set; }
    
        public virtual Gruppa Gruppa { get; set; }
    }
}
