//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pp_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspicanie
    {
        public int id_rasp { get; set; }
        public int id_gruppa { get; set; }
        public int id_trener { get; set; }
        public Nullable<System.DateTime> data_z { get; set; }
        public Nullable<System.TimeSpan> time_z { get; set; }
    
        public virtual Gruppa Gruppa { get; set; }
        public virtual Trener Trener { get; set; }
    }
}
